### ISSUE TITLE
Suggestions for next version

### ISSUE THREAD

**Issue by habbble** [richardneililagan/dtx-simfile-catalog-node#1]
Hey Cards, here are my suggestions for the next release:

- [ ] After each start of a folder DTXFiles folder, there should be a line break, to avoid confusion. And in conjunction to this..
- [ ] All directory names (DTXFiles.xxxxx blah blah) should be in Bold letters

And here are some issues:

- [ ] Some titles are blank, maybe it's an issue with the set.def or the user not using set.def at all. Please see this spreadsheet, I revised this using your parser and added my own stuff: https://docs.google.com/spreadsheets/d/1FAHFBX1tcpAoJKmBFZsXHxjbht5kpfFdozF2_jVIPyE/

That's it for now, thank you very much!

**Comment by richardneililagan** [comment]
Addressed in #3.
